### ISSUE TITLE
Request: set layers/tags recursively

### ISSUE THREAD

**Issue by sleepandpancakes** [nicoplv/smart-layers#1]
It would be nice if there was a built in way to set a layer for a gameobject's children as well as itself

**Comment by nicoplv** [comment]
It's not really the purpose of this "helper", this "helper" objective is only generate static variables to easily access to your layers and tags. But thanks for the proposition.
And you can easily made a function to set layers recursively like that: [https://forum.unity.com/threads/change-gameobject-layer-at-run-time-wont-apply-to-child.10091/#post-72114](https://forum.unity.com/threads/change-gameobject-layer-at-run-time-wont-apply-to-child.10091/#post-72114)
